export type ResourceCategory = "前端" | "爬虫" | "AI" | "工具";

export type ResourceItem = {
  id: string;
  title: string;
  url: string;
  category: ResourceCategory;
  source: string;
  format: "官方文档" | "开放标准" | "学习指南";
  note: string;
  tags: string[];
  featured?: boolean;
};

export const resources: ResourceItem[] = [
  {
    id: "mdn-web",
    title: "MDN Web 技术文档",
    url: "https://developer.mozilla.org/zh-CN/docs/Web",
    category: "前端",
    source: "Mozilla",
    format: "官方文档",
    note: "查 HTML、CSS、JavaScript 和 Web API 时，先从这里确认浏览器行为与标准用法。",
    tags: ["HTML", "CSS", "JavaScript", "Web API"],
    featured: true,
  },
  {
    id: "react-learn",
    title: "React 官方学习指南",
    url: "https://react.dev/learn",
    category: "前端",
    source: "React",
    format: "学习指南",
    note: "从组件、状态到交互，适合建立现代 React 的完整心智模型。",
    tags: ["React", "组件", "状态管理"],
  },
  {
    id: "next-docs",
    title: "Next.js 文档",
    url: "https://nextjs.org/docs",
    category: "前端",
    source: "Next.js",
    format: "官方文档",
    note: "遇到路由、服务端组件、数据获取和部署问题时，直接按当前版本查证。",
    tags: ["Next.js", "App Router", "部署"],
  },
  {
    id: "web-performance",
    title: "Web 性能课程",
    url: "https://web.dev/learn/performance/",
    category: "前端",
    source: "web.dev",
    format: "学习指南",
    note: "从加载、渲染到交互响应，系统补齐网站性能优化的判断依据。",
    tags: ["性能", "Core Web Vitals", "浏览器"],
  },
  {
    id: "mdn-accessibility",
    title: "Web 无障碍指南",
    url: "https://developer.mozilla.org/zh-CN/docs/Web/Accessibility",
    category: "前端",
    source: "Mozilla",
    format: "学习指南",
    note: "检查语义、键盘操作、焦点和动态效果，避免交互只对部分用户可用。",
    tags: ["无障碍", "语义化", "键盘"],
  },
  {
    id: "scrapy-overview",
    title: "Scrapy 快速总览",
    url: "https://docs.scrapy.org/en/latest/intro/overview.html",
    category: "爬虫",
    source: "Scrapy",
    format: "官方文档",
    note: "需要队列、并发、管道和工程化抓取时，用它理解 Scrapy 的完整工作流。",
    tags: ["Python", "Scrapy", "数据管道"],
    featured: true,
  },
  {
    id: "playwright-intro",
    title: "Playwright 入门",
    url: "https://playwright.dev/docs/intro",
    category: "爬虫",
    source: "Microsoft",
    format: "官方文档",
    note: "处理必须运行 JavaScript 的页面，也适合做可靠的端到端自动化测试。",
    tags: ["浏览器自动化", "测试", "JavaScript"],
  },
  {
    id: "robots-rfc",
    title: "RFC 9309：Robots 协议",
    url: "https://www.rfc-editor.org/rfc/rfc9309",
    category: "爬虫",
    source: "RFC Editor",
    format: "开放标准",
    note: "写采集器前先读规则原文，明确 robots.txt 的语法、匹配方式与边界。",
    tags: ["robots.txt", "标准", "合规"],
  },
  {
    id: "beautiful-soup",
    title: "Beautiful Soup 文档",
    url: "https://www.crummy.com/software/BeautifulSoup/bs4/doc/",
    category: "爬虫",
    source: "Beautiful Soup",
    format: "官方文档",
    note: "适合快速解析 HTML，定位节点、清理文本和处理不够规整的页面结构。",
    tags: ["Python", "HTML 解析", "数据清洗"],
  },
  {
    id: "openai-platform",
    title: "OpenAI API 文档",
    url: "https://developers.openai.com/api/docs",
    category: "AI",
    source: "OpenAI",
    format: "官方文档",
    note: "查询模型能力、接口参数、工具调用和生产环境接入方式。",
    tags: ["OpenAI", "API", "模型应用"],
    featured: true,
  },
  {
    id: "huggingface-transformers",
    title: "Transformers 文档",
    url: "https://huggingface.co/docs/transformers/index",
    category: "AI",
    source: "Hugging Face",
    format: "官方文档",
    note: "需要使用、训练或部署开源模型时，从任务、模型与推理管线开始查。",
    tags: ["Transformers", "开源模型", "推理"],
  },
  {
    id: "anthropic-docs",
    title: "Claude 开发文档",
    url: "https://platform.claude.com/docs/en/intro",
    category: "AI",
    source: "Anthropic",
    format: "官方文档",
    note: "对照不同模型的上下文、工具使用和提示词设计，避免只熟悉一种接口。",
    tags: ["Claude", "API", "提示词"],
  },
  {
    id: "github-pages",
    title: "GitHub Pages 指南",
    url: "https://docs.github.com/en/pages/getting-started-with-github-pages/what-is-github-pages",
    category: "工具",
    source: "GitHub",
    format: "官方文档",
    note: "查清静态站点的发布方式、自定义域名、限制和常见部署问题。",
    tags: ["GitHub Pages", "静态站点", "部署"],
  },
  {
    id: "github-actions",
    title: "GitHub Actions 参考",
    url: "https://docs.github.com/en/actions/reference",
    category: "工具",
    source: "GitHub",
    format: "官方文档",
    note: "编写自动构建、测试与发布流程时，用它核对工作流语法和权限设置。",
    tags: ["GitHub Actions", "CI/CD", "自动化"],
  },
];
