export type ResourceCategory = "前端" | "爬虫" | "AI" | "工具";

export type ResourceItem = {
  id: string;
  title: string;
  url: string;
  category: ResourceCategory;
  source: string;
  format: "官方文档" | "开放标准" | "学习指南";
  note: string;
  tags: string[];
  featured?: boolean;
};

export const resources: ResourceItem[] = [
  {
    id: "mdn-web",
    title: "MDN Web 技术文档",
    url: "https://developer.mozilla.org/zh-CN/docs/Web",
    category: "前端",
    source: "Mozilla",
    format: "官方文档",
    note: "查 HTML、CSS、JavaScript 和 Web API 时，先从这里确认浏览器行为与标准用法。",
    tags: ["HTML", "CSS", "JavaScript", "Web API"],
    featured: true,
  },
  {
    id: "react-learn",
    title: "React 官方学习指南",
    url: "https://react.dev/learn",
    category: "前端",
    source: "React",
    format: "学习指南",
    note: "从组件、状态到交互，适合建立现代 React 的完整心智模型。",
    tags: ["React", "组件", "状态管理"],
  },
  {
    id: "next-docs",
    title: "Next.js 文档",
    url: "https://nextjs.org/docs",
    category: "前端",
    source: "Next.js",
    format: "官方文档",
    note: "遇到路由、服务端组件、数据获取和部署问题时，直接按当前版本查证。",
    tags: ["Next.js", "App Router", "部署"],
  },
  {
    id: "web-performance",
    title: "Web 性能课程",
    url: "https://web.dev/learn/performance/",
    category: "前端",
    source: "web.dev",
    format: "学习指南",
    note: "从加载、渲染到交互响应，系统补齐网站性能优化的判断依据。",
    tags: ["性能", "Core Web Vitals", "浏览器"],
  },
  {
    id: "mdn-accessibility",
    title: "Web 无障碍指南",
    url: "https://developer.mozilla.org/zh-CN/docs/Web/Accessibility",
    category: "前端",
    source: "Mozilla",
    format: "学习指南",
    note: "检查语义、键盘操作、焦点和动态效果，避免交互只对部分用户可用。",
    tags: ["无障碍", "语义化", "键盘"],
  },
  {
    id: "scrapy-overview",
    title: "Scrapy 快速总览",
    url: "https://docs.scrapy.org/en/latest/intro/overview.html",
    category: "爬虫",
    source: "Scrapy",
    format: "官方文档",
    note: "需要队列、并发、管道和工程化抓取时，用它理解 Scrapy 的完整工作流。",
    tags: ["Python", "Scrapy", "数据管道"],
    featured: true,
  },
  {
    id: "playwright-intro",
    title: "Playwright 入门",
    url: "https://playwright.dev/docs/intro",
    category: "爬虫",
    source: "Microsoft",
    format: "官方文档",
    note: "处理必须运行 JavaScript 的页面，也适合做可靠的端到端自动化测试。",
    tags: ["浏览器自动化", "测试", "JavaScript"],
  },
  {
    id: "robots-rfc",
    title: "RFC 9309：Robots 协议",
    url: "https://www.rfc-editor.org/rfc/rfc9309",
    category: "爬虫",
    source: "RFC Editor",
    format: "开放标准",
    note: "写采集器前先读规则原文，明确 robots.txt 的语法、匹配方式与边界。",
    tags: ["robots.txt", "标准", "合规"],
  },
  {
    id: "beautiful-soup",
    title: "Beautiful Soup 文档",
    url: "https://www.crummy.com/software/BeautifulSoup/bs4/doc/",
    category: "爬虫",
    source: "Beautiful Soup",
    format: "官方文档",
    note: "适合快速解析 HTML，定位节点、清理文本和处理不够规整的页面结构。",
    tags: ["Python", "HTML 解析", "数据清洗"],
  },
  {
    id: "openai-platform",
    title: "OpenAI API 文档",
    url: "https://developers.openai.com/api/docs",
    category: "AI",
    source: "OpenAI",
    format: "官方文档",
    note: "查询模型能力、接口参数、工具调用和生产环境接入方式。",
    tags: ["OpenAI", "API", "模型应用"],
    featured: true,
  },
  {
    id: "huggingface-transformers",
    title: "Transformers 文档",
    url: "https://huggingface.co/docs/transformers/index",
    category: "AI",
    source: "Hugging Face",
    format: "官方文档",
    note: "需要使用、训练或部署开源模型时，从任务、模型与推理管线开始查。",
    tags: ["Transformers", "开源模型", "推理"],
  },
  {
    id: "anthropic-docs",
    title: "Claude 开发文档",
    url: "https://platform.claude.com/docs/en/intro",
    category: "AI",
    source: "Anthropic",
    format: "官方文档",
    note: "对照不同模型的上下文、工具使用和提示词设计，避免只熟悉一种接口。",
    tags: ["Claude", "API", "提示词"],
  },
  {
    id: "github-pages",
    title: "GitHub Pages 指南",
    url: "https://docs.github.com/en/pages/getting-started-with-github-pages/what-is-github-pages",
    category: "工具",
    source: "GitHub",
    format: "官方文档",
    note: "查清静态站点的发布方式、自定义域名、限制和常见部署问题。",
    tags: ["GitHub Pages", "静态站点", "部署"],
  },
  {
    id: "github-actions",
    title: "GitHub Actions 参考",
    url: "https://docs.github.com/en/actions/reference",
    category: "工具",
    source: "GitHub",
    format: "官方文档",
    note: "编写自动构建、测试与发布流程时，用它核对工作流语法和权限设置。",
    tags: ["GitHub Actions", "CI/CD", "自动化"],
  },
  {
    id: "typescript-handbook",
    title: "TypeScript Handbook",
    url: "https://www.typescriptlang.org/docs/handbook/intro.html",
    category: "前端",
    source: "TypeScript",
    format: "学习指南",
    note: "从日常类型、函数和对象开始，逐步理解 TypeScript 怎样检查 JavaScript 程序。",
    tags: ["TypeScript", "类型系统", "JavaScript"],
  },
  {
    id: "vite-guide",
    title: "Vite 入门指南",
    url: "https://vite.dev/guide/",
    category: "前端",
    source: "Vite",
    format: "官方文档",
    note: "核对项目创建、静态资源、环境变量和生产构建，适合轻量前端项目查阅。",
    tags: ["Vite", "构建工具", "前端工程"],
  },
  {
    id: "wcag-22",
    title: "WCAG 2.2 无障碍规范",
    url: "https://www.w3.org/TR/WCAG22/",
    category: "前端",
    source: "W3C",
    format: "开放标准",
    note: "需要判断键盘、焦点、对比度和动态内容是否可访问时，回到成功标准原文。",
    tags: ["无障碍", "WCAG", "Web 标准"],
  },
  {
    id: "python-robotparser",
    title: "Python urllib.robotparser",
    url: "https://docs.python.org/3/library/urllib.robotparser.html",
    category: "爬虫",
    source: "Python",
    format: "官方文档",
    note: "用标准库读取 robots.txt，并检查指定 User-Agent 是否允许访问某条路径。",
    tags: ["Python", "robots.txt", "标准库"],
  },
  {
    id: "requests-advanced",
    title: "Requests 高级用法",
    url: "https://requests.readthedocs.io/en/stable/user/advanced/",
    category: "爬虫",
    source: "Requests",
    format: "官方文档",
    note: "需要会话、连接复用、预处理请求或 TLS 配置时，按实际请求链路查对应章节。",
    tags: ["Python", "Requests", "HTTP"],
  },
  {
    id: "http-semantics-rfc",
    title: "RFC 9110：HTTP 语义",
    url: "https://www.rfc-editor.org/rfc/rfc9110.html",
    category: "爬虫",
    source: "RFC Editor",
    format: "开放标准",
    note: "核对请求方法、状态码、条件请求和缓存相关字段，避免凭经验猜协议行为。",
    tags: ["HTTP", "状态码", "缓存"],
  },
  {
    id: "openai-evaluation",
    title: "OpenAI 评测最佳实践",
    url: "https://developers.openai.com/api/docs/guides/evaluation-best-practices",
    category: "AI",
    source: "OpenAI",
    format: "学习指南",
    note: "设计样本、判定标准和持续评测流程时，用它检查评测是否贴近真实任务。",
    tags: ["评测", "Evals", "AI 工程"],
  },
  {
    id: "huggingface-evaluate",
    title: "Hugging Face Evaluate 快速导览",
    url: "https://huggingface.co/docs/evaluate/a_quick_tour",
    category: "AI",
    source: "Hugging Face",
    format: "学习指南",
    note: "了解怎样加载指标、组织评测数据，并把计算结果接进模型实验。",
    tags: ["Evaluate", "指标", "模型评测"],
  },
  {
    id: "pro-git",
    title: "Pro Git 中文版",
    url: "https://git-scm.com/book/zh/v2",
    category: "工具",
    source: "Git",
    format: "学习指南",
    note: "从提交、分支到远程协作都有完整解释，适合按问题查，也适合连续阅读。",
    tags: ["Git", "版本控制", "协作"],
  },
  {
    id: "commonmark-spec",
    title: "CommonMark 规范",
    url: "https://spec.commonmark.org/current/",
    category: "工具",
    source: "CommonMark",
    format: "开放标准",
    note: "Markdown 在列表、代码块和链接处出现解析差异时，可以用规范示例核对。",
    tags: ["Markdown", "CommonMark", "内容格式"],
  },
  {
    id: "node-api",
    title: "Node.js API 文档",
    url: "https://nodejs.org/api/",
    category: "工具",
    source: "Node.js",
    format: "官方文档",
    note: "编写构建脚本和命令行工具时，查询文件系统、路径、进程与测试模块。",
    tags: ["Node.js", "API", "构建脚本"],
  },
];
