import { readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const postsDirectory = join(root, "content", "posts");
const outputFile = join(root, "content", "posts.generated.ts");

async function findMarkdownFiles(directory) {
  const entries = await readdir(directory, { withFileTypes: true });
  const files = await Promise.all(entries.map(async (entry) => {
    const path = join(directory, entry.name);
    if (entry.isDirectory()) return findMarkdownFiles(path);
    return entry.isFile() && entry.name.endsWith(".md") ? [path] : [];
  }));
  return files.flat();
}

const files = (await findMarkdownFiles(postsDirectory)).sort();
const entries = await Promise.all(files.map(async (file) => {
  const key = relative(postsDirectory, file).replaceAll("\\", "/");
  const source = (await readFile(file, "utf8")).replace(/\r\n/g, "\n");
  const category = source.match(/^category:\s*(.+)$/m)?.[1].trim().replace(/^['"]|['"]$/g, "");
  const categoryDirectory = key.split("/")[0];
  if (!category || categoryDirectory !== category) {
    throw new Error(`${key}: category must match its directory`);
  }
  return [key, source];
}));

const pathsBySlug = new Map();
for (const [key] of entries) {
  const slug = key.split("/").pop().replace(/\.md$/, "");
  const existingPath = pathsBySlug.get(slug);
  if (existingPath) {
    throw new Error(`Duplicate article slug "${slug}": ${existingPath}, ${key}`);
  }
  pathsBySlug.set(slug, key);
}

const posts = Object.fromEntries(entries);
const output = `// Generated by scripts/generate-posts.mjs. Do not edit by hand.\nexport const rawPosts: Record<string, string> = ${JSON.stringify(posts, null, 2)};\n`;

await writeFile(outputFile, output, "utf8");
console.log(`Generated ${files.length} posts in ${relative(root, outputFile)}`);
