import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";
import { loadContent } from "./content.mjs";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const outputDirectory = join(root, ".generated");
const outputFile = join(outputDirectory, "posts.ts");
const { posts } = await loadContent(root);
const output = `// Generated by scripts/generate-posts.mjs. Do not edit by hand.\nexport const generatedPosts = ${JSON.stringify(posts, null, 2)} as const;\n`;

await mkdir(outputDirectory, { recursive: true });
await writeFile(outputFile, output, "utf8");
console.log(`Generated and validated ${posts.length} posts in ${relative(root, outputFile)}`);
