import { readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const postsDirectory = join(root, "content", "posts");
const outputFile = join(root, "content", "posts.generated.ts");
const files = (await readdir(postsDirectory)).filter((file) => file.endsWith(".md")).sort();
const posts = Object.fromEntries(await Promise.all(files.map(async (file) => [file, await readFile(join(postsDirectory, file), "utf8")])));
const output = `// Generated by scripts/generate-posts.mjs. Do not edit by hand.\nexport const rawPosts: Record<string, string> = ${JSON.stringify(posts, null, 2)};\n`;

await writeFile(outputFile, output, "utf8");
console.log(`Generated ${files.length} posts in ${relative(root, outputFile)}`);
